### ISSUE TITLE
Unifying document refs (related concepts and authoritative sources)

### ISSUE THREAD

**Issue by skalee** [glossarist/glossarist-ruby#10]
Consider this YAML excerpt:

```yaml
---
termid: 112-01-11
term: dimension of a quantity
related:
- type: supersedes
  ref:
    source: IEV
    id: 112-01-11
    version: 2010-01
fra:
  authoritative_source:
  - ref: ISO/IEC Guide 99:2007
    clause: '1.7'
    link: https://www.iso.org/standard/45324.html
    relationship:
      type: modified
      modification: Ajout d'une utilisation spécifique du terme privilégié, ajout
        de renvois dans la définition et la note 4, transfert des exemples 1 et 2
        dans la Note 5 à l'article et ajout d'un nouvel exemple, transfert de l'exemple
        3 dans une nouvelle Note 6 à l'article
    original: ISO/IEC Guide 99:2007, 1.7, modifié – Ajout d'une utilisation spécifique
      du terme privilégié, ajout de renvois dans la définition et la note 4, transfert
      des exemples 1 et 2 dans la Note 5 à l'article et ajout d'un nouvel exemple,
      transfert de l'exemple 3 dans une nouvelle Note 6 à l'article
```

It refers two documents:

1. `{source: IEV, id: 112-01-11, version: 2010-01}` (supersession)
2. `ISO/IEC Guide 99:2007` (authoritative source for French translation)

One is structured and another one is plain text. Questions:

1. Is it possible to have structured ref in authoritative source?
2. Is it possible to have plain text ref in related concepts?
3. Or maybe these are very different kinds of refs and I should keep clear distinction between them (different model classes with different attributes)?
4. Shouldn't clause, link, or original be attributes of structured ref? Or maybe ref should represent document name only, without clause or link (which potentially may depend on clause)?
