### ISSUE TITLE
Glossarist does not provide sufficient attributes for Paneron to function

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-ruby#108]
The Glossarist extension on Paneron requires the following minimal attributes to function:

```yaml
---
data:
  identifier: '2122487'
  localized_concepts:
    eng: 6cb22ee4-dc58-53c2-a948-9fa8575bc687
    fre: 9bc91618-4368-5517-b9d2-051f82712f90
related: []
date_accepted: 2015-10-01
id: fffdf929-a746-3500-bdd2-af076f5acdc0
status: valid
```

Currently, it only provides:
```yaml
---
data:
  localized_concepts:
    eng: 6cb22ee4-dc58-53c2-a948-9fa8575bc687
    fre: 9bc91618-4368-5517-b9d2-051f82712f90
```

This task is to supplement the rest.
