### ISSUE TITLE
Differentiate types of abbreviations (acronym, initialism, truncation, other)

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-ruby#63]
There are a few kinds of "abbreviations" ("Abbreviated term resulting from the omission of some of its letters.").

See this: https://www.iso.org/obp/ui/#iso:std:iso:4:ed-3:v1:en

These are the kinds:
* acronym (Abbreviated complex term made up of letters from the full form of a term and strung together into a sequence pronounced only syllabically)
* initialism (Abbreviated complex term or name made up of the first letters of the term elements.)
* truncation(Shortening of a word by the omission of two or more continuous letters at the end.)
* other (something that doesn't fit into the above categories)

_Originally posted by @ronaldtse in https://github.com/glossarist/glossarist-ruby/issues/62#issuecomment-1542400005_

**Comment by HassanAkbar** [comment]
@ronaldtse We have all of these types in glossarist here (https://github.com/glossarist/glossarist-ruby/blob/main/config.yml#L47-L51), so we can set the type to `abbreviation` and set if it is an `acronym` or `initialism` etc like

```yaml
- type: abbreviation
  initialism: true
  designation: something
```

OR

```yaml
- type: abbreviation
  truncation: true
  designation: something
```

 and for `others` we can leave it just to 

```yaml
- type: abbreviation
  designation: something
```

Is this acceptable or do we need to change something here?
