### ISSUE TITLE
`ManagedCollection#save_to_files` method does not save in the new Glossarist dataset format

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-ruby#84]
Per https://github.com/glossarist/termium/issues/3 :

As described by @HassanAkbar  https://github.com/glossarist/glossarist-ruby/issues/83#issuecomment-1816447057

> we need 2 folders for creating a concept dataset (both folder names are singular)
> 
> * concept
> * localized_concept

In this line: 
https://github.com/glossarist/termium/blob/4b7ce29a7e0199f9766d0027cd081441fd9e2f97/lib/termium/cli.rb#L58

Clearly the `ManagedCollection#save_to_files` method in Glossarist does not export a Concept YAML folder that conforms to this concept dataset description.

Instead it exports to a flat directory structure where the universal concept and the localized concepts are within the same file.

`sources/concepts` in iso-iec-2382 repo ([link](https://github.com/metanorma/iso-iec-2382/tree/main/sources/concepts)):
```
concept-10031778.yaml
concept-10031781.yaml
concept-2120533.yaml
concept-2120534.yaml
...
```

`concept-2120533.yaml`:
```yaml
---
termid: '2120533'
term: network
eng:
  id: '2120533'
  terms:
  - type: expression
  # ...
  definition:
  - content: arrangement of entities and their interconnections
  # ...
fre:
  id: '2120533'
  terms:
  - type: expression
  # ...
```

This task is to update the method so that it exports a Glossarist dataset that is immediately useable by Geolexica.
